export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";
export const LEARN_MORE = "LEARN_MORE";
export const CLOSE_LEARN_MORE = "CLOSE_LEARN_MORE";
export const ADD_TO_CART = "ADD_TO_CART";
export const INC_PRODUCT_QUANTITY = 'INC_PRODUCT_QUANTITY';
export const DEC_PRODUCT_QUANTITY = 'DEC_PRODUCT_QUANTITY';
